### ISSUE TITLE
Segfault in libqt5core

### ISSUE THREAD

**Issue by edpil02** [ProtozeFOSS/KrakenZPlayground#1]
After a lot of compilation difficulties due to libusb headers  ( "libusb_get_interface_association_descriptors   not declared ")  I have a segfault  when i  run the KrakenZplayground  binary.

(gdb) bt
#0  0x00007ffff69017d3 in QIODevice::write(char const*, long long) () from /lib64/libQt5Core.so.5
#1  0x0000000000411a08 in KrakenZDriver::setPumpDuty(unsigned char) ()
#2  0x00000000004266a3 in KrakenZDriver::qt_metacall(QMetaObject::Call, int, void**) ()
#3  0x00007ffff70d5e83 in QQmlObjectOrGadget::metacall(QMetaObject::Call, int, void**) const () from /lib64/libQt5Qml.so.5
#4  0x00007ffff6fd97dc in CallPrecise(QQmlObjectOrGadget const&, QQmlPropertyData const&, QV4::ExecutionEngine*, QV4::CallData*, QMetaObject::Call) () from /lib64/libQt5Qml.so.5
#5  0x00007ffff6fdabfd in QV4::QObjectMethod::callInternal(QV4::Value const*, QV4::Value const*, int) const () from /lib64/libQt5Qml.so.5
#6  0x00007ffff6ff037f in QV4::Moth::VME::interpret(QV4::CppStackFrame*, QV4::ExecutionEngine*, char const*) () from /lib64/libQt5Qml.so.5
#7  0x00007ffff6ff67d8 in QV4::Moth::VME::exec(QV4::CppStackFrame*, QV4::ExecutionEngine*) [clone .part.0] () from /lib64/libQt5Qml.so.5
#8  0x00007ffff6f9e5a6 in QV4::Function::call(QV4::Value const*, QV4::Value const*, int, QV4::ExecutionContext const*) () from /lib64/libQt5Qml.so.5
#9  0x00007ffff70f5d4b in QQmlJavaScriptExpression::evaluate(QV4::CallData*, bool*) () from /lib64/libQt5Qml.so.5
#10 0x00007ffff70b28bf in QQmlBoundSignalExpression::evaluate(void**) () from /lib64/libQt5Qml.so.5

Thanks
Qt5-5.15.2

**Comment by edpil02** [comment]
Solved.
The new  git  push  solves the issue, no more segfault.
Thanks
